server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /specs/ {
        alias /usr/share/nginx/html/specs/;
        add_header Access-Control-Allow-Origin *;
    }
}
